.github/workflows/pr-close.yml, .github/workflows/pr-open.yml
Rename github workflow files.
This PR is the test.
=> ci: renaming files

.github/workflows/pr-open.yml
Just another deploy test.
Please delete options that are not relevant.
With this PR.
=> ci: fix deploy workflow

.github/dependabot.yml, .github/labeler.yml, .github/release.yaml, .github/workflows/pr-label.yml, .github/workflows/release.yml
New test to fix PR release and deploy.
Using this PR
=> ci: add missing files

.github/workflows/pr-open.yml
New release test with PR closing.
With this PR.
=> fix: right github personal token to release job

.github/workflows/merge-main.yml, .github/workflows/pr-close.yml, .github/workflows/pr-open.yml
New worflow tests.
With this pull request.
=> ci: adjust release and merge main flows

.github/workflows/pr-close.yml
Fix release tag not generating based on PR labels.
With this PR.
=> fix: release tag not generating

.github/workflows/merge-main.yml, .github/workflows/pr-close.yml, src/main/java/ca/bc/gov/backendstartapi/dto/ExampleDto.java, src/main/java/ca/bc/gov/backendstartapi/endpoint/CheckEndpoint.java
Fix release version into endpoint and adjust namespaces test and prod.
With this PR.
=> fix: release version not present at check response

.github/workflows/pr-close.yml
Get image promotion working after merging to main.
With pull requests. Lots of them.
=> fix: adjust image promotion not working

test/postman/starting-api.postman_collection.json, test/postman/starting-api.postman_environment.json
Create a set of test cases on Postman to cover the new user API endpoint.
- Create a user with valid data
- Create a user that already exists
- Create a user with invalid data
- Find a user by the first name
- Find a user using a non-existent first name
- Find a user by the last name
- Find a user using a non-existent last name
- Find a user by the first and last name
- Find a user using a non-existent first and last name
-  Find all users
- Delete a user
- Delete a user that does not exist.
- [ x] New feature (non-breaking change which adds functionality)
To run the test import both the environment and collection to you Postman and run the collection with the collection runner selecting the correct environment.
- [ x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ x] I have …
=> feat: add api tests for user endpoint

README.md
Remove brackets around Coverage and Branches badges in the README.
Documentation cleanup.
Open the project's README in a branch containing this change.
=> docs(readme): remove brackets around badges

.github/workflows/merge-main.yml
Enable the workflow to generate a tag without a changelog.
Please delete options that are not relevant.
Using previous Pull Request.
=> update parameters to generate tag without changelog

.github/workflows/merge-main.yml, .github/workflows/pr-open.yml, test/postman/README.md, test/postman/starting-api.postman_collection.json, test/postman/starting-api.postman_environment.json
Added authentication retrieving to all endpoints and created new variables to accommodate credentials.
Fixes # (199)
Tested locally pointing to the environment of PR #42
=> test: add auth to api tests

pom.xml
Upgrade the checkstyle plugin. Request by Dependabot.
Please delete options that are not relevant.
Just the pipeline itself.
=> Build(deps): Bump maven-checkstyle-plugin from 3.2.0 to 3.2.1

.github/workflows/merge-main.yml
Remove a vulnerability related to the [hashicorp/vault-action](https://github.com/hashicorp/vault-action) reinserted in #61.
Fixes [Dependabot alert #5](https://github.com/bcgov/nr-backend-starting-api/security/dependabot/5)
Please delete options that are not relevant.
It hasn't.
=> ci(vault): update hashicorp/vault-action to the latest release

.github/dependabot.yml
Activate Dependabot upgrades for GitHub actions as well.
=> ci(dependabot): activate upgrades for GitHub actions

.github/openshift/deploy.backend.yml, .github/openshift/networkPolicies.yml, .github/workflows/merge-main.yml, .github/workflows/pr-close.yml, .github/workflows/pr-open.yml, .github/workflows/release.yml, Dockerfile, README.md, docker-compose.yml, dockerfile-entrypoint.sh, pom.xml, src/main/java/ca/bc/gov/backendstartapi/endpoint/CheckEndpoint.java, src/main/resources/application.properties, src/test/resources/application.properties, test/postman/README.md, test/postman/oracle-api.postman_collection.json, test/postman/oracle-api.postman_environment.json
Update names and titles to match the repository name change from `nr-backend-starting-api` to `nr-spar-oracle-api`.
Fixes [FSADT2-356](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-356)
- CI changes (naming)
- Documentation changes
=> chore: update things to match the repository's new name

.github/workflows/merge-main.yml
Add action to retrieve vault token from broker.
Fixes the deployment that should be happened on PR #78 
This change will be tested when this PR gets merged.
=> ci: add action to retrieve token from broker

.mvn/google_checks.xml, src/main/java/ca/bc/gov/backendstartapi/endpoint/FundingSourceEndpoint.java
Add `UnusedImports` module to Google Check-style.
This change was tested locally.
=> feat: add check for unused imports

.github/workflows/merge-main.yml
Correct the path to secrets in Vault.
=> ci(vault): correct secrets path

.github/workflows/merge-main.yml, .github/workflows/release.yml, pom.xml
Unite dependencies upgrades from #121, #122 and #123.
=> build(deps): upgrade dependencies
